#!/bin/bash

export GITHUB_WORKSPACE=`pwd`
echo $GITHUB_WORKSPACE
rm -rf build_macos
rm -rf ./SDR++.app
mkdir -p build_macos
cd build_macos
cmake \
  -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=26.0 \
  $GITHUB_WORKSPACE \
  -DOPT_BUILD_AIRSPY_SOURCE=OFF \
  -DOPT_BUILD_RTL_TCP_SOURCE=OFF \
  -DOPT_BUILD_SPYSERVER_SOURCE=OFF \
  -DOPT_BUILD_NETWORK_SOURCE=OFF \
  -DOPT_BUILD_RFSPACE_SOURCE=OFF \
  -DOPT_BUILD_HERMES_SOURCE=OFF \
  -DOPT_BUILD_AIRSPYHF_SOURCE=OFF \
  -DOPT_BUILD_PLUTOSDR_SOURCE=OFF \
  -DOPT_BUILD_BLADERF_SOURCE=ON \
  -DOPT_BUILD_SDRPLAY_SOURCE=OFF \
  -DOPT_BUILD_LIMESDR_SOURCE=OFF \
  -DOPT_BUILD_AUDIO_SINK=OFF \
  -DOPT_BUILD_PORTAUDIO_SINK=ON \
  -DOPT_BUILD_NEW_PORTAUDIO_SINK=ON \
  -DOPT_BUILD_M17_DECODER=OFF \
  -DOPT_BUILD_PERSEUS_SOURCE=OFF \
  -DOPT_BUILD_AUDIO_SOURCE=OFF \
  -DOPT_BUILD_RFNM_SOURCE=OFF \
  -DOPT_BUILD_FOBOSSDR_SOURCE=OFF \
  -DOPT_BUILD_HYDRASDR_SOURCE=OFF \
  -DOPT_BUILD_USRP_SOURCE=ON \
  -DUSE_BUNDLE_DEFAULTS=ON \
  -DCMAKE_BUILD_TYPE=Release
make VERBOSE=1 -j8 usrp_source || exit 1
make VERBOSE=1 -j8 bladerf_source || exit 1
make VERBOSE=1 -j8
cd $GITHUB_WORKSPACE && sh make_macos_bundle.sh ./build_macos ./SDR++.app
