#!/bin/bash

export GITHUB_WORKSPACE=`pwd`
echo $GITHUB_WORKSPACE
rm -rf build_pi
rm -rf ./SDR++.app
mkdir -p build_pi
cd build_pi
cmake \
  $GITHUB_WORKSPACE \
  -DOPT_BUILD_AIRSPY_SOURCE=OFF \
  -DOPT_BUILD_AIRSPYHF_SOURCE=OFF \
  -DOPT_BUILD_BLADERF_SOURCE=OFF \
  -DOPT_BUILD_HERMES_SOURCE=OFF \
  -DOPT_BUILD_PLUTOSDR_SOURCE=OFF \
  -DOPT_BUILD_RFSPACE_SOURCE=OFF \
  -DOPT_BUILD_SPECTRAN_HTTP_SOURCE=OFF \
  -DOPT_BUILD_SPYSERVER_SOURCE=OFF \
  -DOPT_BUILD_USRP_SOURCE=ON \
  -DOPT_BUILD_RIGCTL_CLIENT=OFF \
  -DOPT_BUILD_RIGCTL_SERVER=OFF
  
make VERBOSE=1 -j$(nproc)
